# Generated by Django 3.2.9 on 2021-12-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211204_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_size',
            new_name='has_sizes',
        ),
    ]
